# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantityresponsemodel',
            name='quantity',
            field=models.TextField(),
        ),
    ]
