# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_task', '0002_auto_20180329_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantityresponsemodel',
            name='text_quantity',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quantityresponsemodel',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
